# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: jmagland@flatironinstitute.org
author_name: Jeremy Magland
has_binder: false
has_settings: false
kind: frontend
labextension_name: jpfiddle_extension
project_short_description: A JupyterLab extension for jpfiddle.
python_name: jpfiddle_extension
repository: https://github.com/magland/jpfiddle_extension
test: false

